In [1]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [2]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [3]:
net = simpleNet()

In [4]:
print(net.W)

[[ 1.58751649 -0.60311621  0.48418007]
 [-0.27386733 -0.12511312  0.70151787]]


In [5]:
x = np.array([0.6, 0.9])

In [6]:
p = net.predict(x)

In [7]:
print(p)

[ 0.70602929 -0.47447153  0.92187412]


In [8]:
np.argmax(p)

2

In [9]:
t = np.array([0, 0, 1])

In [10]:
net.loss(x, t)

3.9864665469125846

In [11]:
def f(W):
    return net.loss(x, t)

In [12]:
dW = numerical_gradient(f, net.W)

In [13]:
print(dW)

[[-0.49357321 -0.38303835  0.87661156]
 [-0.74035981 -0.57455752  1.31491734]]
